### ISSUE TITLE
Shibby 的 Mod 自带 DNSCrypt, 为什么还要另外安装呢

### ISSUE THREAD

**Issue by epizza** [cykor/VPNCykoGM#3]
我的网络环境是静态IP，手动设置运营商的DNS：218.2.135.1 61.147.37.1
在开启 DNSCrypt 后，看log路由会自动再添加一个DNS：127.0.0.1#40
在 DNSMasq 中把一些域名强制 127.0.0.1#40 解析就可以了，为什么还要另外安装 DNSCrypt 呢？

**Comment by cykor** [comment]
Shibby内置的DNSCrypt会把127.0.0.1:40设置为第一DNS，并启动strict-order，也就是说所有的域名都先要通过127.0.0.1:40解析。而这一切是硬编码的，无法更改。这样一来会有两个问题：
1. 在我这里，OpenDNS的IP有的时候是封锁的（最近境外IP 443干扰也很频繁），需要先建立VPN链接才能访问。配置文件中使用域名访问VPN，这就成了一个死循环，所以只能把域名替换为IP，这又不方便维护。在VPN由于封锁或服务中断的时候，所有的域名解析都会受到影响。
2. OpenDNS的访问速度肯定是要远远低于运营商DNS速度的，我这里是400ms vs 2 ms。而OpenDNS的CDN设置肯定也不如运营商设置的合理，所以会比较影响解析速度和访问速度。

当然，如果不在乎上述的问题，使用内置的DNSCrypt更加方便。
