### ISSUE TITLE
执行 script.sh 出错，没有 seq 命令。

### ISSUE THREAD

**Issue by kangweiqiang** [cykor/VPNCykoGM#4]
/jffs/vpnc/script.sh: line 103: seq: not found

optware 应该装哪个包才有。

**Comment by cykor** [comment]
用的什么版本的ROM？seq是BusyBox带的命令，opkg里面没有的。

**Comment by kangweiqiang** [comment]
Tomato USB 1.28 ，请教一下 BusyBox 怎么加 seq ？

**Comment by cykor** [comment]
奇怪Tomato USB应该就是全套BusyBox啊。我记得seq好像不是一个单独的binary，晚上回家看看

**Comment by kangweiqiang** [comment]
我装了 tomato shibby，发现也没有 seq 命令。

**Comment by htfei** [comment]
busybox中 seq不支持负数，如 `seq -2 2`
